############################################
# +---------------------------------------+#
# |         Config Revision 17            |#
# +---------------------------------------+#
############################################

# -------------------------------------------------------------------------------------------------------------------
FoodChest:
    type: SUPPLYCRATE # Place a chest down, and the chest will be filled with items
    item: 'CHEST 1 name:&c[&6Foodie_&eChest&c]_&f#124 lore:&7Mmmm,_something_smells_good.|&8Place_the_chest_down_to_obtain_a_pack_of_food! glow:true'
    buy:
        enabled: false
        cost: 0
    message:
        open: '{p}You have opened a &c[&6Foodie &eChest&c] &f#124'
        broadcast: ''
    effect:
        1:
          class: AtomEffect
          radius: 1
          iterations: 30
        2:
          class: Sound
          sound: ENTITY_BAT_TAKEOFF
    reward:
        minimum-rewards: 8
        maximum-rewards: 15
        rewards:
            - 'unique:(),     always:(),           cmd:(heal {player}), display:(gold_block 1 name:&fHeal! lore:&r&eOpen_for_an_instant_heal! glow:true)'
            - 'unique:(),     chance:(1),          item:(cake 1 name:&fThe_cake_is_a_lie!)'
            - 'unique:(),     chance:(1),          item:(apple 1)'
            - 'unique:(),     chance:(1),          item:(golden_apple 1)'
            - 'unique:(),     chance:(1),          item:(bone 1)'
            - 'unique:(),     chance:(1),          item:(bread 1)'
            - 'unique:(),     chance:(1),          item:(melon_slice 1)'
            - 'unique:(),     chance:(1),          item:(ice 1)'
            - 'unique:(),     chance:(1),          item:(snow 1)'
            - 'unique:(),     chance:(1),          item:(melon 1)'
            - 'unique:(),     chance:(1),          item:(dirt 1)'
            - 'unique:(),     chance:(1),          item:(sand 1)'
            - 'unique:(),     chance:(1),          item:(birch_log 1)'
            - 'unique:(),     chance:(1),          item:(cobweb 1)'
            - 'unique:(),     chance:(1),          item:(porkchop 1)'
            - 'unique:(),     chance:(1),          item:(beef 1)'
            - 'unique:(),     chance:(1),          item:(cooked_beef 1)'
            - 'unique:(),     chance:(1),          item:(mushroom_stew 1)'
# -------------------------------------------------------------------------------------------------------------------
FoodPack:
    type: MYSTERYCRATE # Right, or left click to receive rewards
    item: 'minecart 1 name:&c[&6Foodie_&ePack&c]_&f#125 lore:&7Mmmm,_something_smells_good.|&8Right_click_to_receive_a_pack_of_food! glow:true'
    confirmation:
        enabled: true
        accept-button: 'GREEN_STAINED_GLASS_PANE 1 name:&aYes lore:&fClick_here_to_open_{crate}!'
        decline-button: 'RED_STAINED_GLASS_PANE 1 name:&4No'
    buy:
        enabled: false
        cost: 0
    message:
        open: '{p}You have opened a &c[&6Foodie &ePack&c] &f#125'
        broadcast: ''
    effect:
        1:
          class: HeartEffect
        2:
          class: Sound
          sound: ENTITY_BAT_TAKEOFF
    reward:
        minimum-rewards: 3
        maximum-rewards: 3
        rewards:
            - 'unique:(),     always:(),           cmd:(heal {player}), display:(gold_block 1 name:&fHeal! lore:&r&eOpen_for_an_instant_heal! glow:true)'
            - 'unique:(),     chance:(1),          item:(cake 1 name:&fThe_cake_is_a_lie!)'
            - 'unique:(),     chance:(1),          item:(apple 1)'
            - 'unique:(),     chance:(1),          item:(golden_apple 1)'
            - 'unique:(),     chance:(1),          item:(bone 1)'
            - 'unique:(),     chance:(1),          item:(bread 1)'
            - 'unique:(),     chance:(1),          item:(melon_slice 1)'
            - 'unique:(),     chance:(1),          item:(ice 1)'
            - 'unique:(),     chance:(1),          item:(snow 1)'
            - 'unique:(),     chance:(1),          item:(melon 1)'
            - 'unique:(),     chance:(1),          item:(dirt 1)'
            - 'unique:(),     chance:(1),          item:(sand 1)'
            - 'unique:(),     chance:(1),          item:(birch_log 1)'
            - 'unique:(),     chance:(1),          item:(cobweb 1)'
            - 'unique:(),     chance:(1),          item:(porkchop 1)'
            - 'unique:(),     chance:(1),          item:(beef 1)'
            - 'unique:(),     chance:(1),          item:(cooked_beef 1)'
            - 'unique:(),     chance:(1),          item:(mushroom_stew 1)'
# -------------------------------------------------------------------------------------------------------------------
FoodKey:
    type: KEYCRATE # Set this crate to a block, and players may right click the block to use "keys"
    item: 'NETHER_STAR 1 name:&c[&6Foodie_Key&c]_&f#1 lore:&7Mmmm,_something_smells_good.|&8Right_click_a_chest_to_receive_a_pack_of_food! glow:true'
    animation: 'none'
    display-name: '&c[&6Foodie Key&c] &f#1'
    holographic:
        - '{crate-name}'
        - '{lore:1}'
    confirmation:
        enabled: true
        accept-button: 'GREEN_STAINED_GLASS_PANE 1 name:&aYes lore:&fClick_here_to_open_{crate}!'
        decline-button: 'RED_STAINED_GLASS_PANE 1 name:&4No'
    preview:
        enabled: true
        rows: 2
    buy:
        enabled: false
        cost: 0
    message:
        open: '{p}You have opened a {crate}'
        broadcast: ''
    effect:
        1:
          class: Original
          category: PERSISTENT
        2:
          class: Sound
          category: OPEN
          sound: ENTITY_BAT_TAKEOFF
    reward:
        minimum-rewards: 3
        maximum-rewards: 3
        rewards:
            - 'unique:(),     always:(),           cmd:(heal {player}), display:(gold_block 1 name:&fHeal! lore:&r&eOpen_for_an_instant_heal! glow:true)'
            - 'unique:(),     chance:(1),          item:(cake 1 name:&fThe_cake_is_a_lie!)'
            - 'unique:(),     chance:(1),          item:(apple 1)'
            - 'unique:(),     chance:(1),          item:(golden_apple 1)'
            - 'unique:(),     chance:(1),          item:(bone 1)'
            - 'unique:(),     chance:(1),          item:(bread 1)'
            - 'unique:(),     chance:(1),          item:(melon_slice 1)'
            - 'unique:(),     chance:(1),          item:(ice 1)'
            - 'unique:(),     chance:(1),          item:(snow 1)'
            - 'unique:(),     chance:(1),          item:(melon 1)'
            - 'unique:(),     chance:(1),          item:(dirt 1)'
            - 'unique:(),     chance:(1),          item:(sand 1)'
            - 'unique:(),     chance:(1),          item:(birch_log 1)'
            - 'unique:(),     chance:(1),          item:(cobweb 1)'
            - 'unique:(),     chance:(1),          item:(porkchop 1)'
            - 'unique:(),     chance:(1),          item:(beef 1)'
            - 'unique:(),     chance:(1),          item:(cooked_beef 1)'
            - 'unique:(),     chance:(1),          item:(mushroom_stew 1)'
# -------------------------------------------------------------------------------------------------------------------
# An example of a key crate with animations (Roulette)
FoodKeyT2:
    type: KEYCRATE # Set this crate to a block, and players may right click the block to use "keys"
    item: 'NETHER_STAR 1 name:&c[&6Foodie_&eKey&c]_&f#2 lore:&7Mmmm,_something_smells_good.|&8Right_click_a_chest_to_receive_a_pack_of_food! glow:true'
    animation: 'ROULETTE'
    display-name: '&c[&6Foodie Crate&c] &f#2'
    holographic:
        - '{crate-name}'
        - '{lore:1}'
    confirmation:
        enabled: true
        accept-button: 'GREEN_STAINED_GLASS_PANE 1 name:&aYes lore:&fClick_here_to_open_{crate}!'
        decline-button: 'RED_STAINED_GLASS_PANE 1 name:&4No'
    preview:
        enabled: true
        rows: 2
    buy:
        enabled: false
        cost: 0
    message:
        open: '{p}You have opened a {crate}'
        broadcast: ''
    effect:
        1:
          class: Original
          category: PERSISTENT
        2:
          class: Sound
          category: ANIMATION
          sound: BLOCK_WOOD_PLACE
        3:
          class: Sound
          sound: ENTITY_BAT_TAKEOFF
          CATEGORY: END
    reward:
        minimum-rewards: 1
        maximum-rewards: 1
        rewards:
            - 'unique:(),     always:(),           cmd:(heal {player}), display:(gold_block 1 name:&fHeal! lore:&r&eOpen_for_an_instant_heal! glow:true)'
            - 'unique:(),     chance:(1),          item:(cake 1 name:&fThe_cake_is_a_lie!)'
            - 'unique:(),     chance:(1),          item:(apple 1)'
            - 'unique:(),     chance:(1),          item:(golden_apple 1)'
            - 'unique:(),     chance:(1),          item:(bone 1)'
            - 'unique:(),     chance:(1),          item:(bread 1)'
            - 'unique:(),     chance:(1),          item:(melon_slice 1)'
            - 'unique:(),     chance:(1),          item:(ice 1)'
            - 'unique:(),     chance:(1),          item:(snow 1)'
            - 'unique:(),     chance:(1),          item:(melon 1)'
            - 'unique:(),     chance:(1),          item:(dirt 1)'
            - 'unique:(),     chance:(1),          item:(sand 1)'
            - 'unique:(),     chance:(1),          item:(birch_log 1)'
            - 'unique:(),     chance:(1),          item:(cobweb 1)'
            - 'unique:(),     chance:(1),          item:(porkchop 1)'
            - 'unique:(),     chance:(1),          item:(beef 1)'
            - 'unique:(),     chance:(1),          item:(cooked_beef 1)'
            - 'unique:(),     chance:(1),          item:(mushroom_stew 1)'
# -------------------------------------------------------------------------------------------------------------------
# An example of a key crate with animations (CSGO)
FoodKeyT3:
    type: KEYCRATE # Set this crate to a block, and players may right click the block to use "keys"
    item: 'NETHER_STAR 1 name:&c[&6Foodie_&eKey&c]_&f#3 lore:&7Mmmm,_something_smells_good.|&8Right_click_a_chest_to_receive_a_pack_of_food! glow:true'
    animation: 'CSGO'
    display-name: '&c[&6Foodie Key&c] &f#3'
    holographic:
        - '{crate-name}'
        - '{lore:1}'
    confirmation:
        enabled: true
        accept-button: 'GREEN_STAINED_GLASS_PANE 1 name:&aYes lore:&fClick_here_to_open_{crate}!'
        decline-button: 'RED_STAINED_GLASS_PANE 1 name:&4No'
    preview:
        enabled: true
        rows: 2
    buy:
        enabled: false
        cost: 0
    message:
        open: '{p}You have opened a {crate}'
        broadcast: ''
    effect:
        1:
          class: Original
          category: PERSISTENT
        2:
          class: Sound
          category: ANIMATION
          sound: BLOCK_WOOD_PLACE
        3:
          class: Sound
          sound: ENTITY_BAT_TAKEOFF
          CATEGORY: END
    reward:
        minimum-rewards: 1
        maximum-rewards: 1
        rewards:
            - 'unique:(),     always:(),           cmd:(heal {player}), display:(gold_block 1 name:&fHeal! lore:&r&eOpen_for_an_instant_heal! glow:true)'
            - 'unique:(),     chance:(1),          item:(cake 1 name:&fThe_cake_is_a_lie!)'
            - 'unique:(),     chance:(1),          item:(apple 1)'
            - 'unique:(),     chance:(1),          item:(golden_apple 1)'
            - 'unique:(),     chance:(1),          item:(bone 1)'
            - 'unique:(),     chance:(1),          item:(bread 1)'
            - 'unique:(),     chance:(1),          item:(melon_slice 1)'
            - 'unique:(),     chance:(1),          item:(ice 1)'
            - 'unique:(),     chance:(1),          item:(snow 1)'
            - 'unique:(),     chance:(1),          item:(melon 1)'
            - 'unique:(),     chance:(1),          item:(dirt 1)'
            - 'unique:(),     chance:(1),          item:(sand 1)'
            - 'unique:(),     chance:(1),          item:(birch_log 1)'
            - 'unique:(),     chance:(1),          item:(cobweb 1)'
            - 'unique:(),     chance:(1),          item:(porkchop 1)'
            - 'unique:(),     chance:(1),          item:(beef 1)'
            - 'unique:(),     chance:(1),          item:(cooked_beef 1)'
            - 'unique:(),     chance:(1),          item:(mushroom_stew 1)'

